### ISSUE TITLE
Is it possible to increase the rendering levels?

### ISSUE THREAD

**Issue by Trashmonk** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#20]
I have been using the OS MasterMap Topography WMTS service in QGIS. Recently I decided to use the view the vector data directly via PostGIS. Everything is working well except that the styling stops rendering at 1:4000. In the documentation it states;

"We recommend viewing the map between 1:500 and 1:4000 for maximum legibility and we have set the
minimum viewing scale at 1:4000"

Using the OS MasterMap Topography WMTS service you are able to zoom out to the full extent of the UK with styling for all levels. Is this styling ever going to be made available on GitHub or only through the WMTS service?

Thank you

**Comment by TimJMartin** [comment]
Hi @Trashmonk 

So the OS Maps API WMTS is made up of a number of OS products and not just OSMM Topography Layer - the list is [here]( https://apidocs.os.uk/docs/layer-information). It currently uses Strategi, OS VectorMap District and OS VectorMap Local. So there are several different products to process, manage and style. 

However we have recently released [OS Open Zoomstack ](https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-zoomstack.html) so that you only need to manage one product. Zoomstack can be used for the zoom layers above OSMM Topography Layer.

There are stylesheets for Zoomstack [here](https://github.com/OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets) which include QGIS QML files.

I hope that helps

Tim

**Comment by Trashmonk** [comment]
Hi Tim,

Thanks for the response. Okay that all makes sense. I am currently using a combination of Zoomstack and Mastermap Topo, so its good to hear this is the best solution.

Thanks.
