### ISSUE TITLE
Non-compliance to Style Guide

### ISSUE THREAD

**Issue by sab56** [OrdnanceSurvey/OSMM-Topography-Layer-stylesheets#28]
The styles defined in these stylesheets do not conform to the styles in the style guide published by the OS. The differences between the ArcMap layer file styles and the styles defined in the style guide are shown in the attached PDF document.
[osmm_topo_arcmap_styling_issues.pdf](https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets/files/6684893/osmm_topo_arcmap_styling_issues.pdf)

**Comment by egil1978** [comment]
Hi @sab56 
Thank for getting in touch. It looks like the style guide might need updating in places. Let me take a closer look and ill get back to you shortly. :)

**Comment by egil1978** [comment]
Hi @sab56, would you be ok pointing us to the style guide you are refering to with the images in your PDF? The style guide we are looking at does not appear to have the same pattern images that you have screenshot. Many thanks.

**Comment by sab56** [comment]
Hi @egil1978, the pattern images in my PDF were not cut and pasted from the style guide, I constructed them in ArcMap from the SVG definitions in the style guide - [https://www.ordnancesurvey.co.uk/documents/os-mastermap-topography-layer-cartographic-styling-update.pdf](url).

**Comment by egil1978** [comment]
Hi sab56, thanks for getting back to us. There does seem to be some discrepancies between how the style guide describes the SVG's and the SVG's we use as part of our stylesheets. The style guide is about 20 years old now and was put together when OSMM Topo was first released in 2001. Since then the styles have evolved somewhat and sadly it seems the style guide has not been updated to reflect this. We are constantly improving all of our stylesheets and will take the issues you have raised into consideration when we next update them.

**Comment by sab56** [comment]
The stylesheets appear to be an extremely poor implementation of the style guide. The ArcMap layer files are particularly bad, containing numerous errors, e.g. coniferous tree symbol used for both coniferous and non coniferous trees.

**Comment by egil1978** [comment]
Hi @sab56, we are looking at the stylesheets now and will amend the doc accordingly.

**Comment by sab56** [comment]
Why has this issue been closed? Non of the problems have been fixed.
